### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by Nek** [captbaritone/markdown.today#2]
Could you please add it?
I'd like to do some changes to the code and probably deploy the editor to my own server but the license is missing making legality of my actions questionable.

**Comment by captbaritone** [comment]
Sorry for missing this issue. I've added a LICENSE file clarifying that I release this under MIT. If you have any other questions feel free to file more issues, I'd be curious to hear what you are trying to do. If you need different abstraction layers to achieve what you are trying to do, I'd be interested to hear.

**Comment by Nek** [comment]
No worries and thanks a lot for the license update. 

I have some ideas for a specific use case, a journal for people with mood disorders. I'll create an issue with features suggestions.
