### ISSUE TITLE
Search system 

### ISSUE THREAD

**Issue by javifr** [captbaritone/markdown.today#23]
Sine kind of search system that could look for words on titles or body text would be nice.

**Comment by captbaritone** [comment]
Have you tried this icon? 
<img width="469" alt="screen shot 2018-08-07 at 3 38 52 pm" src="https://user-images.githubusercontent.com/162735/43806268-16895056-9a58-11e8-84ca-4929c33c6f90.png">

Is there something more specific that you are looking for?
