### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by Nek** [captbaritone/markdown.today#4]
Hello Jordan,
following our discussion here goes what I want from journaling app.
I have a bipolar mood disorder. Keeping track of my thoughts, moods and medications is indispensable. I want to be reminded about writing a note, to be able to write down aforementioned things, to navigate through notes and to see diagrams built from recorded metrics/tags.

To break it down I need:
- reminders
- text and metrics notes
- search based navigation
- data visualisation

The available apps are either too specific, lack some features or/and have features I don't need.

I've figured out the best way is to use a barebones open source note taking app I can improve as I see fit. The main requirement is data in plain text format. Then I can use ad hoc hash tags for metrics (#mood:3, #anxious etc.) and build diagrams using some external tool. Reminders are also not essential, I can set them using my smartphone's standard app.

Having said that the features I'd like to have are:
1. separate files for separate notes (not sure)
2. plain text notes
3. editable note's date
4. note's template
5. some kind of search

I have more ideas for UI/UX but they are less important.

As far as I can see plain text notes go against project's idea and search is a complex thing.
Your thoughts?

**Comment by captbaritone** [comment]
Thanks for outlining all of this! Sounds like a very valuable project. There are some overlaps between what you want to do and what I want to do. Namely:

* Add search
* Add the ability to edit the date of an entry

I'll create separate issues to track these.

I'm afriaid there's not a good way for an app like Markdown Today (which has no server component) to do reminders. Would it be possible to use a separate app to trigger the reminders? Not as nice, but it could work. I imagine there are services which will send recurring emails/texts and you could have it include a link to Markdown Today.

For the remaining requests would you mind opening separate issues for each? That way we can discuss them individually.

Thanks again for your interest!

**Comment by Nek** [comment]
Looks like you've skipped part of my message:
```
Reminders are also not essential, I can set them using my smartphone's standard app.
```
So using a separate app is exactly what I'm going to do.

Glad to see we have some similar features in mind. I'll open the issues later.

**Comment by captbaritone** [comment]
Ahh whoops! I've filed the two issues and tagged you in them.
